name: Decompile Minecraft

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Minecraft version (e.g. 1.21.8)'
        required: true
      side:
        description: 'client or server'
        required: true

jobs:
  decompile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Prepare variables
      id: prep
      run: |
        VERSION="${{ github.event.inputs.version }}"
        SIDE="${{ github.event.inputs.side }}"
        SIDE_UPPER=$(echo "$SIDE" | tr '[:lower:]' '[:upper:]')
        BRANCH="${VERSION}-${SIDE}"

        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "SIDE=$SIDE" >> $GITHUB_ENV
        echo "SIDE_UPPER=$SIDE_UPPER" >> $GITHUB_ENV
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV

    - name: Decompile with Mojang mappings
      run: |
        java -jar MinecraftDecompiler.jar \
          --version "$VERSION" \
          --side "$SIDE_UPPER" \
          --decompile \
          --decompiled-output mojang

    - name: Download and extract Yarn and Intermediary Tiny v2 mappings
      run: |
        mkdir -p mappings/yarn mappings/intermediary

        curl -sL "https://maven.fabricmc.net/net/fabricmc/yarn/$VERSION+build.1/yarn-$VERSION+build.1-v2.jar" -o yarn-mappings.jar
        unzip -p yarn-mappings.jar mappings/mappings.tiny > mappings/yarn.tinyv2
        rm yarn-mappings.jar

        curl -sL "https://maven.fabricmc.net/net/fabricmc/intermediary/$VERSION/intermediary-$VERSION-v2.jar" -o intermediary-mappings.jar
        unzip -p intermediary-mappings.jar mappings/mappings.tiny > mappings/intermediary.tinyv2
        rm intermediary-mappings.jar

    - name: Remap to Yarn and Intermediary (placeholder)
      run: |
        java -jar MinecraftDecompiler.jar \
          --version "$VERSION" \
          --side "$SIDE_UPPER" \
          --mapping-path mappings/yarn.tinyv2
          --decompile \
          --decompiled-output yarn \
          
        java -jar MinecraftDecompiler.jar \
          --version "$VERSION" \
          --side "$SIDE_UPPER" \
          --mapping-path mappings/intermediary.tinyv2
          --decompile \
          --decompiled-output intermediary \

        #mkdir yarn
        #mkdir intermediary
        #echo "// placeholder files" > yarn/Placeholder.java
        #echo "// placeholder files" > intermediary/Placeholder.java

    - name: Clone private repo branch
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        git clone https://x-access-token:${{ secrets.SECRET_PAT }}@github.com/MediumCraft/Minecraft.git private-repo
        cd private-repo

        # Delete and recreate branch
        git checkout --orphan "$BRANCH"
        git rm -rf .
        cd ..

    - name: Copy decompiled sources into private repo
      run: |
        rm -rf private-repo/*
        cp -r mojang private-repo/mojang
        cp -r yarn private-repo/yarn
        cp -r intermediary private-repo/intermediary

    - name: Commit and push
      run: |
        cd private-repo
        git add .
        git commit -m "Decompiled $VERSION ($SIDE)"
        git push -f origin "$BRANCH"
